import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import AuthGuard from "@/componets/Auth";
import { Providers } from './Providers'
=======
import { Providers } from "./Providers";
>>>>>>> 8ab1d59881b5f6684313698e17cd559c230069b1

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "9 Mileon",
  description: "Getting you to financial stability",
=======
  title: "9 Mileon - Internet Banking",
  description: "Generated by create next app",
>>>>>>> 8ab1d59881b5f6684313698e17cd559c230069b1
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
  
<<<<<<< HEAD
        <Providers>
          {children}
        </Providers>
=======
      <Providers>{children}</Providers>
>>>>>>> 8ab1d59881b5f6684313698e17cd559c230069b1
    
      </body>
    </html>
  );
}
